cc_binary(
	name = "stefanproblem_bazel",
	srcs = ["main.cpp",],
	deps = [":stefanProblem",]
)

cc_library(
	name = "stefanProblem",
	srcs = ["stefanProblem.cpp",],
	hdrs = ["stefanProblem.h",],
	visibility = ["//visibility:public"]
)
